/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2022;

import edd.Archivo;
import edd.Cuenta;
import edd.LSL;
import edd.Multilistas;
import edd.Nodo;
import edd.NodoArbol;

import menucuentas.RegistrarCuenta;
import menucuentas.EliminarCuenta;
import menucuentas.MostrarInformacionCuenta;
import menucuentas.ModificarCuenta;

import proyecto2022.Interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author mxsrxm
 */
public class Interfaz extends javax.swing.JFrame
{
    public static Archivo i;

    /**
     * Creates new form Interfaz
     */
    public Interfaz()
    {
        initComponents();
        
        i = Archivo.leer();
        
        if (i != null)
        {
            crearCuenta();
        } else
        {
            i = new Archivo();
        }
        
    }
    
    public static Nodo getRaiz()
    {
        return i.getRaiz();
    }
    
    
    public void crearCuenta()
    {
        jPanelCuentaCuenta.removeAll();
        if (i.getRaiz() != null)
        {
            javax.swing.JFrame parent = this;
            
            Nodo aux = i.getRaiz();
            
            while (aux != null)
            {
                JButton btn = new JButton(aux.getEtiqueta());
                jPanelCuentaCuenta.add(btn);
                btn.addActionListener(new ActionListener()
                {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                        //new (parent, true, btn.getText()).setVisible(true);
                    }
                });
                aux = aux.getSig();
            }
        }
        jPanelCuentaCuenta.updateUI();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenuCuentas = new javax.swing.JPopupMenu();
        jMenuItemRegistrarCuenta = new javax.swing.JMenuItem();
        jMenuItemEliminarCuenta = new javax.swing.JMenuItem();
        jMenuItemModificarCuenta = new javax.swing.JMenuItem();
        jMenuItemMostrarInformacionCuenta = new javax.swing.JMenuItem();
        jPopupMenuCarpetas = new javax.swing.JPopupMenu();
        jMenuItemNuevaCarpeta = new javax.swing.JMenuItem();
        jMenuItemEliminarCarpeta = new javax.swing.JMenuItem();
        jMenuItemModificarCarpeta = new javax.swing.JMenuItem();
        jMenuItemMostrarCarpetas = new javax.swing.JMenuItem();
        jPopupMenuCorreos = new javax.swing.JPopupMenu();
        jMenuItemNuevoCorreo = new javax.swing.JMenuItem();
        jMenuItemEliminarCorreo = new javax.swing.JMenuItem();
        jMenuItemModificarCorreo = new javax.swing.JMenuItem();
        jMenuItemMoverCorreo = new javax.swing.JMenuItem();
        jScrollPaneCarpetas = new javax.swing.JScrollPane();
        jButtonMenuCuentas = new javax.swing.JButton();
        jButtonMenuCarpetas = new javax.swing.JButton();
        jButtonMenuCorreos = new javax.swing.JButton();
        jScrollPaneCuentas = new javax.swing.JScrollPane();
        jPanelCuentaCuenta = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDestinatario = new javax.swing.JLabel();
        jLabelContenido = new javax.swing.JLabel();
        jLabelAsunto = new javax.swing.JLabel();
        jScrollPaneCorreos = new javax.swing.JScrollPane();
        jButtonBuscar = new javax.swing.JButton();

        jMenuItemRegistrarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        jMenuItemRegistrarCuenta.setText("Registrar Cuenta");
        jMenuItemRegistrarCuenta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemRegistrarCuentaActionPerformed(evt);
            }
        });
        jPopupMenuCuentas.add(jMenuItemRegistrarCuenta);

        jMenuItemEliminarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menos.png"))); // NOI18N
        jMenuItemEliminarCuenta.setText("Eliminar Cuenta");
        jPopupMenuCuentas.add(jMenuItemEliminarCuenta);

        jMenuItemModificarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jMenuItemModificarCuenta.setText("Modificar Cuenta");
        jPopupMenuCuentas.add(jMenuItemModificarCuenta);

        jMenuItemMostrarInformacionCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/expediente.png"))); // NOI18N
        jMenuItemMostrarInformacionCuenta.setText("Mostrar Información");
        jMenuItemMostrarInformacionCuenta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemMostrarInformacionCuentaActionPerformed(evt);
            }
        });
        jPopupMenuCuentas.add(jMenuItemMostrarInformacionCuenta);

        jMenuItemNuevaCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        jMenuItemNuevaCarpeta.setText("Nueva Carpeta");
        jPopupMenuCarpetas.add(jMenuItemNuevaCarpeta);

        jMenuItemEliminarCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menos.png"))); // NOI18N
        jMenuItemEliminarCarpeta.setText("Eliminar Carpeta");
        jPopupMenuCarpetas.add(jMenuItemEliminarCarpeta);

        jMenuItemModificarCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jMenuItemModificarCarpeta.setText("Modificar Carpeta");
        jPopupMenuCarpetas.add(jMenuItemModificarCarpeta);

        jMenuItemMostrarCarpetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/expediente.png"))); // NOI18N
        jMenuItemMostrarCarpetas.setText("Mostrar Carpetas");
        jPopupMenuCarpetas.add(jMenuItemMostrarCarpetas);

        jMenuItemNuevoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agregar.png"))); // NOI18N
        jMenuItemNuevoCorreo.setText("Nuevo Correo");
        jPopupMenuCorreos.add(jMenuItemNuevoCorreo);

        jMenuItemEliminarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menos.png"))); // NOI18N
        jMenuItemEliminarCorreo.setText("Eliminar Correo");
        jPopupMenuCorreos.add(jMenuItemEliminarCorreo);

        jMenuItemModificarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        jMenuItemModificarCorreo.setText("Modificar Correo");
        jPopupMenuCorreos.add(jMenuItemModificarCorreo);

        jMenuItemMoverCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/desplazamiento.png"))); // NOI18N
        jMenuItemMoverCorreo.setText("Mover Correo");
        jPopupMenuCorreos.add(jMenuItemMoverCorreo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Correo Equipo 1");
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneCarpetas.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneCarpetas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carpetas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 0, 18))); // NOI18N

        jButtonMenuCuentas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMenuCuentas.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButtonMenuCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lista.png"))); // NOI18N
        jButtonMenuCuentas.setText("Menú Cuentas");
        jButtonMenuCuentas.setComponentPopupMenu(jPopupMenuCuentas);
        jButtonMenuCuentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMenuCuentasActionPerformed(evt);
            }
        });

        jButtonMenuCarpetas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMenuCarpetas.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButtonMenuCarpetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lista.png"))); // NOI18N
        jButtonMenuCarpetas.setText("Menú Carpetas");
        jButtonMenuCarpetas.setComponentPopupMenu(jPopupMenuCarpetas);
        jButtonMenuCarpetas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMenuCarpetasActionPerformed(evt);
            }
        });

        jButtonMenuCorreos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMenuCorreos.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButtonMenuCorreos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lista.png"))); // NOI18N
        jButtonMenuCorreos.setText("Menú Correos");
        jButtonMenuCorreos.setComponentPopupMenu(jPopupMenuCorreos);
        jButtonMenuCorreos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonMenuCorreosActionPerformed(evt);
            }
        });

        jScrollPaneCuentas.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneCuentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cuentas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 0, 18))); // NOI18N

        jPanelCuentaCuenta.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPaneCuentas.setViewportView(jPanelCuentaCuenta);

        jButtonSalir.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSalirActionPerformed(evt);
            }
        });

        jTextFieldBuscar.setToolTipText("Búscar correos por asunto");
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextFieldBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contenido del Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setText("Destinatario:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setText("Asunto:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("Contenido:");

        jLabelDestinatario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDestinatario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelContenido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContenido.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelAsunto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAsunto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneCorreos.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneCorreos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 0, 18))); // NOI18N

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jButtonBuscar.setText("Búscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMenuCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMenuCarpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneCarpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMenuCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalir)
                                .addGap(128, 128, 128))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonMenuCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMenuCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPaneCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonMenuCarpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneCarpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuCuentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMenuCuentasActionPerformed
    {//GEN-HEADEREND:event_jButtonMenuCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuCuentasActionPerformed

    private void jButtonMenuCarpetasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMenuCarpetasActionPerformed
    {//GEN-HEADEREND:event_jButtonMenuCarpetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuCarpetasActionPerformed

    private void jButtonMenuCorreosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonMenuCorreosActionPerformed
    {//GEN-HEADEREND:event_jButtonMenuCorreosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuCorreosActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSalirActionPerformed
    {//GEN-HEADEREND:event_jButtonSalirActionPerformed
        Archivo.guardar(i);
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextFieldBuscarActionPerformed
    {//GEN-HEADEREND:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jMenuItemRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemRegistrarCuentaActionPerformed
    {//GEN-HEADEREND:event_jMenuItemRegistrarCuentaActionPerformed
        new RegistrarCuenta(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarCuentaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonBuscarActionPerformed
    {//GEN-HEADEREND:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jMenuItemMostrarInformacionCuentaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemMostrarInformacionCuentaActionPerformed
    {//GEN-HEADEREND:event_jMenuItemMostrarInformacionCuentaActionPerformed
        crearCuenta();
    }//GEN-LAST:event_jMenuItemMostrarInformacionCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonMenuCarpetas;
    private javax.swing.JButton jButtonMenuCorreos;
    private javax.swing.JButton jButtonMenuCuentas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAsunto;
    private javax.swing.JLabel jLabelContenido;
    private javax.swing.JLabel jLabelDestinatario;
    private javax.swing.JMenuItem jMenuItemEliminarCarpeta;
    private javax.swing.JMenuItem jMenuItemEliminarCorreo;
    private javax.swing.JMenuItem jMenuItemEliminarCuenta;
    private javax.swing.JMenuItem jMenuItemModificarCarpeta;
    private javax.swing.JMenuItem jMenuItemModificarCorreo;
    private javax.swing.JMenuItem jMenuItemModificarCuenta;
    private javax.swing.JMenuItem jMenuItemMostrarCarpetas;
    private javax.swing.JMenuItem jMenuItemMostrarInformacionCuenta;
    private javax.swing.JMenuItem jMenuItemMoverCorreo;
    private javax.swing.JMenuItem jMenuItemNuevaCarpeta;
    private javax.swing.JMenuItem jMenuItemNuevoCorreo;
    private javax.swing.JMenuItem jMenuItemRegistrarCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCuentaCuenta;
    private javax.swing.JPopupMenu jPopupMenuCarpetas;
    private javax.swing.JPopupMenu jPopupMenuCorreos;
    private javax.swing.JPopupMenu jPopupMenuCuentas;
    private javax.swing.JScrollPane jScrollPaneCarpetas;
    private javax.swing.JScrollPane jScrollPaneCorreos;
    private javax.swing.JScrollPane jScrollPaneCuentas;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
